### ISSUE TITLE
reopen the connection

### ISSUE THREAD

**Issue by liorg2** [jakutis/rserve-client#5]
hello, thanks so much for your library- its great.

can i leave the connection open without closing it? any risk?
does it have any timeout / ttl?

thanks

**Comment by jakutis** [comment]
@liorg2 If you leave the connection open, then the forked RServe process will also be left until the node process exits.

It does not have any timeout/ttl logic. Only since version 0.3.5 (released today), client.evaluate creates a new connection to Rserve, if the connection was closed - lost or the Rserve process was restarted.
